import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ratelimiter.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Ratelimiter.io is the easiest way to add rate limiting to your app.
        </h1>

        <div className={styles.description}>
          <a href="https://github.com/petehunt/ratelimiter">Learn more</a>
        </div>
      </main>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  return {
    redirect: {
      permanent: false,
      destination: "https://github.com/petehunt/ratelimiter",
    },
  };
}
